---
title: "DA on features"
author: "Florent Chuffart"
date: "`r Sys.Date()`"
output:
  rmarkdown::html_document:
    toc: true
    toc_float: true
    toc_depth: 3
    number_sections: true
---


```{r header, child="header.Rmd"}
```

```{r}
if (!exists("prefix")) {prefix = "tiles"}
prefix2 = "da"
```

- prefix="`r prefix`" is used to reference the files generated by the pipeline.

```
prefix="`r prefix`" ; rmarkdown::render("04_da.Rmd", output_file=paste0("04_da_", prefix, ".html"))
```


```{r samples, child="samples.Rmd"}
```


# DA

##  Raw counts

```{r raw_counts, fig.height=3}
raw_counts_summary = read.table(paste0(prefix, "_count.txt.summary"), header=TRUE, row.names=1)
colnames(raw_counts_summary) = sub(paste0(".*", gse, "\\.([^.]+)_end\\.to\\.end.*"), "\\1", colnames(raw_counts_summary))
raw_counts_summary = raw_counts_summary[!apply(raw_counts_summary==0, 1, all),]
layout(matrix(1:3, 1), respect=TRUE)
cols = c(
  "#E63946",  # rouge
  "#F4A261",  # orange
  "#E9C46A",  # jaune
  "#2A9D8F",  # vert/bleu
  "#457B9D",  # bleu
  "#6D597A",  # violet
  "#B56576",  # vieux rose
  "#588157"   # vert
)
barplot(col=cols, as.matrix(raw_counts_summary), las=2)
barplot(col=cols, prop.table(as.matrix(raw_counts_summary), margin=2), las=2)
plot.new()
legend("topleft", legend=rownames(raw_counts_summary), fill=cols, bty="n")

raw_counts = read.table(paste0(prefix, "_count.txt"), header=TRUE)
rownames(raw_counts) = raw_counts[,1]
pf = raw_counts[,1:6]
raw_counts = as.matrix(raw_counts[,-(1:6)])
colnames(raw_counts) = sub(paste0(".*", gse, "\\.([^.]+)_end\\.to\\.end.*"), "\\1", colnames(raw_counts))
head(raw_counts[,1:3])
tail(raw_counts[,1:3])
dim( raw_counts)

```


## Filtering features

```{r density, results="verbatim"}
layout(matrix(1:2, 1), respect=TRUE)
plot(density(log2(raw_counts)+1))
# raw_counts = raw_counts[!apply(raw_counts<2048, 1, all),]
raw_counts = raw_counts[!apply(raw_counts<32, 1, all),]
plot(density(log2(raw_counts)+1))
dim(raw_counts)
```



# Volcano plots


```{r volcano, results="verbatim"}

if (!all(e$gsm %in% colnames(raw_counts))) {stop("problem gsm vs. colnames(raw_counts)")}
countData = raw_counts[,e$gsm]
colnames(countData) = rownames(e)
colData = e[colnames(countData),]
# Vérifie que les noms de colonnes correspondent
if (!all(colnames(countData) == rownames(colData))) {stop("probleme data vs. e")}

layout(matrix(1:2,1), respect=TRUE)

for (k in factoi) {
  # k = "sprayed_status"
  print(k)
  frmula = formula(paste("~", k))
  dds <- DESeq2::DESeqDataSetFromMatrix(
    countData = countData,
    colData = colData,
    design = frmula
  )
  dds <- DESeq2::DESeq(dds)
  res <- DESeq2::results(dds)

  res = res[!is.na(res$pvalue),]
  res = res[!is.na(res$padj),]
  plot(res$log2FoldChange, -log10(res$pvalue), xlab="l2fc", ylab="-log10(pval)", main=frmula)
  plot(res$log2FoldChange, -log10(res$padj)  , xlab="l2fc", ylab="-log10(padj)", main=frmula)

  res = res[order(res$log2FoldChange), ]
  idx = rownames(res)[res$padj< 0.05]

  print(cbind(pf[idx,2:4], res[idx, c("log2FoldChange", "pvalue", "padj") ]))

  WriteXLS::WriteXLS



}
```




# Session Information

```{r results="verbatim"}
sessionInfo()
```



























