---
title: "TSS profiles protein-coding transcripts"
author: "Florent Chuffart"
date: "`r Sys.Date()`"
output:
  rmarkdown::html_document:
    toc: true
    toc_float: true
    toc_depth: 3
    number_sections: true
---


```{r, echo=FALSE, eval=TRUE}
knitr::opts_chunk$set(collapse=TRUE, comment = "#>", fig.width=9, fig.height=6, eval=TRUE, echo=FALSE, results="hide")
source("config")
source("config.R")
source("common.R")
```

```{r}
# score_filenames = paste0("/home/chuffarf/projects/datashare/", gse, "/", samples, "_end-to-end_trim30_bowtie2_", species, "_", annotation, "_", version, "_srt.bam")
# bam_file = score_filenames[4]
#   bam_file <- "/home/chuffarf/projects/datashare/atacseq_govin_2023spoatacseq1/veg1_end-to-end_trim30_bowtie2_Saccharomyces_cerevisiae_UCSC_sacCer3_srt.bam"

library(GenomicRanges)
library(VplotR)

# if (!exists("mimportPEBamFiles")) {mimportPEBamFiles = memoise::memoise(importPEBamFiles, cache=cachem::cache_mem(max_size = 10*1024 * 1024^2))}
# if (!exists("mgetFragmentsDistribution")) {mgetFragmentsDistribution = memoise::memoise(getFragmentsDistribution, cache=cachem::cache_mem(max_size = 10*1024 * 1024^2))}
# if (!exists("mplotVmat")) {mplotVmat = memoise::memoise(plotVmat, cache=cachem::cache_mem(max_size = 10*1024 * 1024^2))}


if (!exists("mimportPEBamFiles"))         {mimportPEBamFiles           = memoise::memoise(importPEBamFiles         );}
if (!exists("mcomputeVmat"))              {mcomputeVmat                = memoise::memoise(computeVmat              );}
# if (!exists("mgetFragmentsDistribution")) {mgetFragmentsDistribution   = memoise::memoise(getFragmentsDistribution );}
# if (!exists("mplotVmat"))                 {mplotVmat                   = memoise::memoise(plotVmat                 );}




for (sample in samples[c(13,15,17,19)]) {
  cat("***********************")
  cat(sample)
  write("***********************", stderr())
  write(sample, stderr())

  bam_file = paste0("/home/chuffarf/projects/datashare/", gse, "/", sample, "_end-to-end_trim30_bowtie2_", species, "_", annotation, "_", version, "_srt.bam")
  # bam_file = "datashare/cutntag_sayou_curie/raw/2021988/analysis_results/N300C04/mapping/N300C04_SC5314_Assembly22_custom_filtered.bam"

  fragments = mimportPEBamFiles(
      bam_file, 
      # where=genes,
      cores=32,
      shift_ATAC_fragments=TRUE
  )
}










genes_file = paste0("~/projects/datashare/genomes/", species, "/", annotation, "/", version, "/Annotation/Genes/genes.bed")
genes = read.table(genes_file, header=FALSE)
head(genes)
# split and convert per region
genes = GRanges(
  seqnames = genes$V1,
  ranges = IRanges(start = ifelse(genes$V6=="+", genes$V2, genes$V3),
                   end =   ifelse(genes$V6=="+", genes$V2, genes$V3) + 1,
                   names = genes$V4),
  strand = genes$V6
)



for (sample in samples[c(13,15,17,19)]) {
  cat("***********************")
  cat(sample)
  write("***********************", stderr())
  write(sample, stderr())


  bam_file = paste0("/home/chuffarf/projects/datashare/", gse, "/", sample, "_end-to-end_trim30_bowtie2_", species, "_", annotation, "_", version, "_srt.bam")
  # bam_file = "datashare/cutntag_sayou_curie/raw/2021988/analysis_results/N300C04/mapping/N300C04_SC5314_Assembly22_custom_filtered.bam"

  fragments = mimportPEBamFiles(
      bam_file, 
      # where=genes,
      cores=32,
      shift_ATAC_fragments=TRUE
  )
  # fragments


  df <- getFragmentsDistribution(
      fragments, 
      extend_granges = c(-1500, 1500),
      genes, 
      cores=cores
  )
  #> Warning in as.cls(x): NAs introduced by coercion
  #> Warning in as.cls(x): NAs introduced by coercion
  #> Warning in as.cls(x): NAs introduced by coercion
  p <- ggplot(df, aes(x = x, y = y)) + geom_line() + theme_ggplot2() +
       labs(title = sample)
  plot(p)
  #> Warning: 

  Vmat <- mcomputeVmat(
    fragments,  
    granges = genes,
    xlims = c(-700, 700), 
    cores=32
  )

  pdf("vmat1.pdf")
  image(as.matrix(Vmat))
  dev.off()


  Vmat <- normalizeVmat(Vmat, fragment, genes, verbose = TRUE)
  pdf("vmat2.pdf")
  image(as.matrix(Vmat))
  dev.off()

  if (any(is.infinite(Vmat) | is.na(Vmat))) 
        Vmat[is.infinite(Vmat) | is.na(Vmat)] <- 0
    class(Vmat) <- c("Vmat", class(Vmat))

  pdf("vmat3.pdf")
  brk = quantile(as.matrix(Vmat), probs=seq(0,1,.1))
  plot(density(as.matrix(Vmat)))
  abline(v=brk)
  crp = colorRampPalette(c("black", "green"))(length(brk)-1)
  image(as.matrix(Vmat), breaks=brk, col=crp )
  dev.off()

  pdf(paste0("vmat_", sample, ".pdf"))
  p <- plotVmat(
    Vmat,
    color=crp
    # x = fragments,  
    # granges = genes,
    # xlims = c(-700, 700)
    # cores=cores, 
    ) +
       labs(title = sample)
  plot(p)
  dev.off()




  # p <- mplotVmat(
  #   Vmat
  #   # x = fragments,  
  #   # granges = genes,
  #   # xlims = c(-700, 700)
  #   # # cores=cores, 
  #   ) +
  #      labs(title = sample)
  # plot(p)
}
```


# Session Information

```{r results="verbatim"}
sessionInfo()
date()
```



























